select
    id as pelicula_id,
    trim(regexp_replace("Name", '\s*\(\d{4}\)\s*$', '')) as titulo,
    "Name" as titulo_completo,
    "Release Date" as fecha_estreno,
    extract(year from "Release Date")::int as anio,
    (extract(year from "Release Date")::int / 10) * 10 as decada,
    "IMDB URL" as imdb_url,
    "unknown" as g_desconocido,
    "Action" as g_accion,
    "Adventure" as g_aventura,
    "Animation" as g_animacion,
    "Children's" as g_infantil,
    "Comedy" as g_comedia,
    "Crime" as g_crimen,
    "Documentary" as g_documental,
    "Drama" as g_drama,
    "Fantasy" as g_fantasia,
    "Film-Noir" as g_film_noir,
    "Horror" as g_terror,
    "Musical" as g_musical,
    "Mystery" as g_misterio,
    "Romance" as g_romance,
    "Sci-Fi" as g_ciencia_ficcion,
    "Thriller" as g_thriller,
    "War" as g_belica,
    "Western" as g_western,
    ("unknown" + "Action" + "Adventure" + "Animation" + "Children's" + "Comedy" + "Crime" + "Documentary" + "Drama" + "Fantasy" + "Film-Noir" + "Horror" + "Musical" + "Mystery" + "Romance" + "Sci-Fi" + "Thriller" + "War" + "Western") as n_generos
from {{ ref('peliculas') }}
